
select 

domain_flag,
cast(order_date_key as INT64) as order_date_key,
marketplace,
analytic_business_unit,
analytic_super_category,
analytic_vertical,
seller_id,
lower(trim(brand)) as brand,
city_tier,
zone,
is_alpha_seller,
az_seller_type,
torso_tail_flag,
manufacturer_flag,
priority_vertical_flag,
kam_nkam_flag,
service_profile,
price_bucket,
branded_flag,
brand_tier,
brand_type,
is_priority_brand,
cast(gmv as numeric) as gmv,
units,
cast(fsp as numeric) as fsp,
cast(mrp as numeric) as mrp,
fbf_units,
cast(sla as numeric) as sla,
cast(o2d as numeric) as o2d,
d0_units,
d1_units,
d2_units,
d4_units,
d6_units,
rto_units,
cast(rto_gmv as numeric) as rto_gmv,
rvp_units,
cast(rvp_gmv as numeric) as rvp_gmv,
ru_den,
ru_num,
pq_rated_units,
cast(pq_num as numeric) as pq_num,
pq_rated_good_pq_units,
pq_rating_4_units,
pq_rating_3_8_units,
pq_rating_3_85_units,
pq_rating_3_9_units,
pq_rated_hygiene_pq_units,
pq_unrated_units,
pq_lt_5_rated_units,
fk_price_npi,
comp_price_npi,
fk_comp,
az_comp,
search_ppvs,
cast(ly_gmv as numeric) as ly_gmv,
ly_units,
cast(sds_pure_az as numeric) as sds_pure_az,
cast(sds_oos_attribution_pure_az as numeric) as sds_oos_attribution_pure_az,
cast(msku_count as numeric) as msku_count,
cast(output_fes_weighted_asp as numeric) as output_fes_weighted_asp,
cast(output_bau_weighted_asp as numeric) as output_bau_weighted_asp,
d2c_flag,
manufacturer_priority_flag,
age_range,
event_type,
event_name,
transacting_selection_count,
analytic_category,
primary_ppvs,
lp_search_ppvs,
merch_and_ad_ppvs,
reco_ppvs,
ly_primary_ppvs,
ly_lp_search_ppvs,
ly_merch_and_ad_ppvs,
ly_reco_ppvs,
new_selection,
cast(m_dw as INT64) as m_dw,
cast(cdw as INT64) as cdw ,
cast(dw as INT64) as dw ,
cast(csds_sds_units as numeric) as csds_sds_units,
cast(csds_units as numeric) as csds_units,
cast(source_cluster_sale as numeric) as source_cluster_sale,
cast(fr_cluster_source_cluster_sale as numeric) as fr_cluster_source_cluster_sale,
cast(dr_cluster_source_cluster_sale as numeric) as dr_cluster_source_cluster_sale,
cast(destination_cluster_sale as numeric) as destination_cluster_sale,
cast(fr_cluster_destination_cluster_sale as numeric) as fr_cluster_destination_cluster_sale,
cast(dr_cluster_destination_cluster_sale as numeric) as dr_cluster_detination_cluster_sale,
cust_category_type, 
cust_category_name, 
orders, 
customers,
input_bau_weighted_asp,
input_fes_weighted_asp,
 cy_mtd_orders,
 cy_mtd_customers,
 ly_mtd_orders,
 ly_mtd_customers,
 fk_cd,
az_cd,
wfcp,
wccp,
op_sp_num, 
op_sp_den, 
ip_sp_num, 
ip_sp_den


from 

(

select 

domain_flag,
order_date_key,
marketplace,
analytic_business_unit,
analytic_super_category,
analytic_vertical,
seller_id,
brand,
city_tier,
zone,
is_alpha_seller,
az_seller_type,
torso_tail_flag,
manufacturer_flag,
priority_vertical_flag,
kam_nkam_flag,
service_profile,
price_bucket,
branded_flag,
brand_tier,
brand_type,
is_priority_brand,
gmv,
units,
fsp,
mrp,
fbf_units,
sla,
o2d,
d0_units,
d1_units,
d2_units,
d4_units,
d6_units,
rto_units,
rto_gmv,
rvp_units,
rvp_gmv,
ru_den,
ru_num,
pq_rated_units,
pq_num,
pq_rated_good_pq_units,
pq_rating_4_units,
pq_rating_3_8_units,
pq_rating_3_85_units,
pq_rating_3_9_units,
pq_rated_hygiene_pq_units,
pq_unrated_units,
pq_lt_5_rated_units,
fk_price_npi,
comp_price_npi,
fk_comp,
az_comp,
search_ppvs,
ly_gmv,
ly_units,
sds_pure_az,
sds_oos_attribution_pure_az,
msku_count,
output_fes_weighted_asp,
output_bau_weighted_asp,
d2c_flag,
manufacturer_priority_flag,
age_range,
ed.event_type as event_type,
ed.event_name as event_name,
transacting_selection_count,
'' as analytic_category,
0 as primary_ppvs,
0 as lp_search_ppvs,
0 as merch_and_ad_ppvs,
0 as reco_ppvs,
0 as ly_primary_ppvs,
0 as ly_lp_search_ppvs,
0 as ly_merch_and_ad_ppvs,
0 as ly_reco_ppvs,
new_selection,
0 as m_dw,
0 as cdw,
0 as dw,
csds_sds_units,
csds_units,
source_cluster_sale,
fr_cluster_source_cluster_sale,
dr_cluster_source_cluster_sale,
destination_cluster_sale,
fr_cluster_destination_cluster_sale,
dr_cluster_destination_cluster_sale,
cust_category_type, 
cust_category_name, 
orders, 
customers,
input_bau_weighted_asp,
input_fes_weighted_asp,
 cy_mtd_orders,
 cy_mtd_customers,
 ly_mtd_orders,
 ly_mtd_customers,
 fk_cd,
az_cd,
wfcp,
wccp,
op_sp_num, 
op_sp_den, 
ip_sp_num, 
ip_sp_den


from 
bigfoot_external_neo.analytics_cdo__bgm_overall_summary_2025_fact as bo
left join 
 fdp_uploads.ds_fkint_analytics_cdo_events_dates_final_1_0 as ed
 on
bo.order_date_key=ed.order_date

where order_date_key not in (20250229)


union all 

select 

domain_flag,
order_date_key,
marketplace,
analytic_business_unit,
analytic_super_category,
analytic_vertical,
seller_id,
brand,
city_tier,
zone,
is_alpha_seller,
az_seller_type,
torso_tail_flag,
manufacturer_flag,
priority_vertical_flag,
kam_nkam_flag,
service_profile,
price_bucket,
branded_flag,
brand_tier,
brand_type,
is_priority_brand,
gmv,
units,
fsp,
mrp,
fbf_units,
sla,
o2d,
d0_units,
d1_units,
d2_units,
d4_units,
d6_units,
rto_units,
rto_gmv,
rvp_units,
rvp_gmv,
ru_den,
ru_num,
pq_rated_units,
pq_num,
pq_rated_good_pq_units,
pq_rating_4_units,
pq_rating_3_8_units,
pq_rating_3_85_units,
pq_rating_3_9_units,
pq_rated_hygiene_pq_units,
pq_unrated_units,
pq_lt_5_rated_units,
fk_price_npi,
comp_price_npi,
fk_comp,
az_comp,
search_ppvs,
ly_gmv,
ly_units,
sds_pure_az,
sds_oos_attribution_pure_az,
msku_count,
output_fes_weighted_asp,
output_bau_weighted_asp,
d2c_flag,
manufacturer_priority_flag,
age_range,
ee.event_type as event_type,
ee.event_name as event_name,
transacting_selection_count,
'' as analytic_category,
0 as primary_ppvs,
0 as lp_search_ppvs,
0 as merch_and_ad_ppvs,
0 as reco_ppvs,
0 as ly_primary_ppvs,
0 as ly_lp_search_ppvs,
0 as ly_merch_and_ad_ppvs,
0 as ly_reco_ppvs,
new_selection,
0 as m_dw,
0 as cdw,
0 as dw,
csds_sds_units,
csds_units,
source_cluster_sale,
fr_cluster_source_cluster_sale,
dr_cluster_source_cluster_sale,
destination_cluster_sale,
fr_cluster_destination_cluster_sale,
dr_cluster_destination_cluster_sale,
'' as cust_category_type, 
'' as cust_category_name, 
0 as orders, 
0 as customers,
input_bau_weighted_asp,
input_fes_weighted_asp,
 0 as cy_mtd_orders,
 0 as cy_mtd_customers,
 0 as ly_mtd_orders,
 0 as ly_mtd_customers,

fk_cd,
az_cd,
wfcp,
wccp,
0 as op_sp_num, 
0 as op_sp_den, 
0 as ip_sp_num, 
0 as ip_sp_den

from 
bigfoot_external_neo.analytics_cdo__bgm_overall_summary_2024_fact as bi
left join 
 fdp_uploads.ds_fkint_analytics_cdo_events_dates_final_1_0 as ee
 on
bi.order_date_key=ee.order_date

where order_date_key not in (20250229)

union all 

select 

domain_flag,
cast(order_date_key as INT64) as order_date_key,
marketplace,
analytic_business_unit,
analytic_super_category,
analytic_vertical,
seller_id,
brand,
city_tier,
zone,
is_alpha_seller,
az_seller_type,
cast(0 as BOOLEAN) as torso_tail_flag,
 '' as manufacturer_flag,   
'' as priority_vertical_flag,
kam_nkam_flag,
service_profile,
price_bucket,
branded_flag,
brand_tier,
'' as brand_type,
'' as is_priority_brand,
gmv,
units,
fsp,
mrp,
fbf_units,
sla,
o2d,
d0_units,
d1_units,
d2_units,
d4_units,
d6_units,
rto_units,
rto_gmv,
rvp_units,
rvp_gmv,
ru_den,
ru_num,
pq_rated_units,
pq_num,
pq_rated_good_pq_units,
pq_rating_4_units,
pq_rating_3_8_units,
pq_rating_3_85_units,
pq_rating_3_9_units,
pq_rated_hygiene_pq_units,
pq_unrated_units,
pq_lt_5_rated_units,
fk_price_npi,
comp_price_npi,
fk_comp,
az_comp,
search_ppvs,
ly_gmv,
ly_units,
sds_pure_az,
sds_oos_attribution_pure_az,
msku_count,
output_fes_weighted_asp,
output_bau_weighted_asp,
d2c_flag,
'' as manufacturer_priority_flag,
'' as age_range,
ed.event_type as event_type,
ed.event_name as event_name,
transacting_selection_count,
'' as analytic_category,
0 as primary_ppvs,
0 as lp_search_ppvs,
0 as merch_and_ad_ppvs,
0 as reco_ppvs,
0 as ly_primary_ppvs,
0 as ly_lp_search_ppvs,
0 as ly_merch_and_ad_ppvs,
0 as ly_reco_ppvs,
new_selection,
 m_dw,
 cdw,
 dw,
0.0 as csds_sds_units,
0.0 as csds_units,
0.0 as source_cluster_sale,
0.0 as fr_cluster_source_cluster_sale,
0.0 as dr_cluster_source_cluster_sale,
0.0 as destination_cluster_sale,
0.0 as fr_cluster_destination_cluster_sale,
0.0 as dr_cluster_destination_cluster_sale,
'' as cust_category_type, 
'' as cust_category_name, 
0 as orders, 
0 as customers,
input_bau_weighted_asp,
input_fes_weighted_asp,
0 as cy_mtd_orders,
 0 as cy_mtd_customers,
 0 as ly_mtd_orders,
 0 as ly_mtd_customers,
 0 as fk_cd,
0 as az_cd,
0 as wfcp,
0 as wccp,
0 as op_sp_num, 
0 as op_sp_den, 
0 as ip_sp_num, 
0 as ip_sp_den

from 
bigfoot_external_neo.analytics_cdo__home_overall_summary1_fact as ho

left join 
 fdp_uploads.ds_fkint_analytics_cdo_events_dates_final_1_0 as ed
 on
ho.order_date_key=ed.order_date
where order_date_key not in (20250229)


union all 


select 

domain_flag,
order_date_key,
marketplace,
analytic_business_unit,
analytic_super_category,
analytic_vertical,
seller_id,
brand,
city_tier,
zone,
is_alpha_seller,
az_seller_type,
cast(0 as BOOLEAN) as torso_tail_flag,
 '' as manufacturer_flag,
'' as priority_vertical_flag,
kam_nkam_flag,
service_profile,
price_bucket,
branded_flag,
brand_tier,
'' as brand_type,
'' as is_priority_brand,
gmv,
units,
fsp,
mrp,
fbf_units,
sla,
o2d,
d0_units,
d1_units,
d2_units,
d4_units,
d6_units,
rto_units,
rto_gmv,
rvp_units,
rvp_gmv,
ru_den,
ru_num,
pq_rated_units,
pq_num,
pq_rated_good_pq_units,
pq_rating_4_units,
pq_rating_3_8_units,
pq_rating_3_85_units,
pq_rating_3_9_units,
pq_rated_hygiene_pq_units,
pq_unrated_units,
pq_lt_5_rated_units,
fk_price_npi,
comp_price_npi,
fk_comp,
az_comp,
search_ppvs,
ly_gmv,
ly_units,
sds_pure_az,
sds_oos_attribution_pure_az,
msku_count,
output_fes_weighted_asp,
output_bau_weighted_asp,
d2c_flag,
'' as manufacturer_priority_flag,
'' as age_range,
ed.event_type as event_type,
ed.event_name as event_name,
0 as transacting_selection_count,
analytic_category,
0 as primary_ppvs,
0 as lp_search_ppvs,
0 as merch_and_ad_ppvs,
0 as reco_ppvs,
0 as ly_primary_ppvs,
0 as ly_lp_search_ppvs,
0 as ly_merch_and_ad_ppvs,
0 as ly_reco_ppvs,
new_selection,
m_dw,
cdw,
dw,
0.0 as csds_sds_units,
0.0 as csds_units,
0.0 as source_cluster_sale,
0.0 as fr_cluster_source_cluster_sale,
0.0 as dr_cluster_source_cluster_sale,
0.0 as destination_cluster_sale,
0.0 as fr_cluster_destination_cluster_sale,
0.0 as dr_cluster_destination_cluster_sale,
'' as cust_category_type, 
'' as cust_category_name, 
0 as orders, 
0 as customers,
input_bau_weighted_asp,
input_fes_weighted_asp,
0 as cy_mtd_orders,
 0 as cy_mtd_customers,
 0 as ly_mtd_orders,
 0 as ly_mtd_customers,
fk_cd,
az_cd,
wfcp,
wccp,
0 as op_sp_num, 
0 as op_sp_den, 
0 as ip_sp_num, 
0 as ip_sp_den

from 

bigfoot_external_neo.analytics_cdo__furniture_overall_summary1_fact as fu
left join 
 fdp_uploads.ds_fkint_analytics_cdo_events_dates_final_1_0 as ed
 on
fu.order_date_key=ed.order_date
where order_date_key not in (20250229) 


union all 

select 

domain_flag,
order_date_key,
marketplace,
analytic_business_unit,
analytic_super_category,
analytic_vertical,
seller_id,
lower(trim(brand)) as brand,
city_tier,
zone,
is_alpha_seller,
az_seller_type,
torso_tail_flag,
manufacturer_flag,
priority_vertical_flag,
kam_nkam_flag,
service_profile,
price_bucket,
branded_flag,
brand_tier,
brand_type,
is_priority_brand,
0 as gmv,
0 as units,
0 as fsp,
0 as mrp,
0 as fbf_units,
0.0 as sla,
0.0 as o2d,
0 as d0_units,
0 as d1_units,
0 as d2_units,
0 as d4_units,
0 as d6_units,
0 as rto_units,
0 as rto_gmv,
0 as rvp_units,
0 as rvp_gmv,
0 as ru_den,
0 as ru_num,
0 as pq_rated_units,
0 as pq_num,
0 as pq_rated_good_pq_units,
0 as pq_rating_4_units,
0 as pq_rating_3_8_units,
0 as pq_rating_3_85_units,
0 as pq_rating_3_9_units,
0 as pq_rated_hygiene_pq_units,
0 as pq_unrated_units,
0 as pq_lt_5_rated_units,
0 as fk_price_npi,
0 as comp_price_npi,
0 as fk_comp,
0 as az_comp,
0 as search_ppvs,
0 as ly_gmv,
0 as ly_units,
0 as sds_pure_az,
0 as sds_oos_attribution_pure_az,
0 as msku_count,
0 as output_fes_weighted_asp,
0 as output_bau_weighted_asp,
d2c_flag,
manufacturer_priority_flag,
'' as age_range,
ed.event_type as event_type,
ed.event_name as event_name,
0 as transacting_selection_count,
'' as analytic_category,
 primary_ppvs,
lp_search_ppvs,
merch_and_ad_ppvs,
reco_ppvs,
ly_primary_ppvs,
ly_lp_search_ppvs,
ly_merch_and_ad_ppvs,
ly_reco_ppvs,
0 as new_selection,
0  as m_dw,
0  as cdw,
0 as dw,
0.0 as csds_sds_units,
0.0 as csds_units,
0.0 as source_cluster_sale,
0.0 as fr_cluster_source_cluster_sale,
0.0 as dr_cluster_source_cluster_sale,
0.0 as destination_cluster_sale,
0.0 as fr_cluster_destination_cluster_sale,
0.0 as dr_cluster_destination_cluster_sale,
'' as cust_category_type, 
'' as cust_category_name, 
0 as orders, 
0 as customers,
0.0 as input_bau_weighted_asp,
0.0 as input_fes_weighted_asp,
0 as cy_mtd_orders,
 0 as cy_mtd_customers,
 0 as ly_mtd_orders,
 0 as ly_mtd_customers,
  0 as fk_cd,
0 as az_cd,
0 as wfcp,
0 as wccp,
0 as op_sp_num, 
0 as op_sp_den, 
0 as ip_sp_num, 
0 as ip_sp_den

from 
bigfoot_external_neo.analytics_cdo__ppv_overall_summary_fact ppv

left join 
 fdp_uploads.ds_fkint_analytics_cdo_events_dates_final_1_0 as ed
 on
ppv.order_date_key=ed.order_date
where order_date_key not in (20250229) 

 ) as bgmh_furniture_ppv_bq_fact
